package com.CourseRegClient.Service;
	
import java.sql.Connection;


import java.util.Properties;
import java.util.Random;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;

/**
* Welcome to Random Password Generator!!
*
* @author  Group 4
* @version 1.0
* @name :  Random Password Generator
* @description : This Random Password Generator Service Client request email id of user and email a auto-generated password.
* @since   2015-11-17
**/
public class RandomPasswordGen {
	
	private static char[] array = {'a','b','c','d','e','f','g','h','i','j','k','l','m','@','$','&','_','n','o','p','q','r','s','t','u','v','w','x','y','z','@','$','&','_','A','B','C','D','F','G','H','I','J','K','L','M','@','$','&','_','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
	
	/**
	 * 
	 * This function returns the randomly generated password  
	 * 
	 */
	private static char getRandomPassword(){
		return array[random(array.length)];
	}
	/**
	 * 
	 * This function provides the length of the array generated 
	 *  
	 */
	private static int random(int length){
		return new Random().nextInt(length);
	}
	/**
	 * 
	 * This function uses stringbuilder function and appends random characters from the array of size 5. 
	 *  
	 *  
	 */
	private static String PasswordGen(){
		
			StringBuilder sb = new StringBuilder();
			int size = 8;
			for(int i=0;i<size;i++){
				sb.append(getRandomPassword());
			}
			
			
			String Password = sb.toString();
			return Password;
			
	}
	/**
	 * This function uses SMTP protocol to send an email. 
	 * Body of the email will be Randomly generated password and TO adddress will be user input emailID
	 *  
	 */
	public static String sendemail(String email){
		
		String temppwd = PasswordGen();
		final String username = "studentcoursereg@gmail.com";
		final String password = "group4@123";
		Properties Myproperties = new Properties();
		Myproperties.put("mail.smtp.auth", "true");
		Myproperties.put("mail.smtp.starttls.enable", "true");
		Myproperties.put("mail.smtp.host", "smtp.gmail.com");
		Myproperties.put("mail.smtp.port", "587");
		
		Session Mysession = Session.getInstance(Myproperties,
				new javax.mail.Authenticator() {
					protected PasswordAuthentication getPasswordAuthentication() {
						return new PasswordAuthentication(username, password);
					}
		});
		
		try{
			
			Message Mymessage = new MimeMessage(Mysession);
			Mymessage.setFrom(new InternetAddress("studentcoursereg@gmail.com"));
			Mymessage.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(email));
			Mymessage.setSubject("Credentials : Autogenerated password");
			Mymessage.setContent("Your temporary password is: " + temppwd,"text/plain; charset=utf-8");
			Transport.send(Mymessage);
			return temppwd;
			
			
			
		}
		catch (MessagingException e){
			throw new RuntimeException(e);
			
		}
	}
	
}



